apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: conntracker
spec:
  selector:
    matchLabels:
      app: conntracker
  template:
    metadata:
      labels:
        app: conntracker
    spec:
      tolerations:
      - operator: Exists  # Tolerate all taints
      serviceAccountName: conntracker
      hostNetwork: true
      containers:
      - name: tracker
        image: fchrgrib/conntracker:latest
        securityContext:
          capabilities:
            add: ["BPF", "NET_ADMIN", "SYS_ADMIN"]
          privileged: true
        env:
        - name: KUBECONFIG
          value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        - name: bpf-fs
          mountPath: /sys/fs/bpf
        - name: kernel-headers
          mountPath: /usr/src/linux-headers
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: bpf-fs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: kernel-headers
        hostPath:
          path: /usr/src/linux-headers-$(uname -r)
          type: Directory