apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: conntracker
spec:
  selector:
    matchLabels:
      app: conntracker
  template:
    metadata:
      labels:
        app: conntracker
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      
      serviceAccountName: conntracker
      hostNetwork: true
      containers:
      - name: tracker
        image: fchrgrib/conntracker:latest
        securityContext:
          capabilities:
            add: ["BPF", "NET_ADMIN", "SYS_ADMIN"]
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        - name: bpf-fs
          mountPath: /sys/fs/bpf
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: bpf-fs
        hostPath:
          path: /sys/fs/bpf
          type: Directory