apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: conntracker
spec:
  selector:
    matchLabels:
      app: conntracker
  template:
    metadata:
      labels:
        app: conntracker
    spec:
      tolerations:
      - operator: Exists
      serviceAccountName: conntracker
      hostNetwork: true
      hostPID: true
      containers:
      - name: tracker
        image: fchrgrib/conntracker:latest
        securityContext:
          capabilities:
            add: ["BPF", "NET_ADMIN", "SYS_ADMIN", "SYS_PTRACE", "SYS_RESOURCE"]
          privileged: true
        env:
        - name: USE_INCLUSTER_CONFIG
          value: "true"
        # Fix the Kubernetes config approach
        - name: KUBECONFIG
          value: ""  # Empty value to force in-cluster config
        # Add debugging
        - name: DEBUG
          value: "true"
        # Increase verbosity if your app supports it
        - name: LOG_LEVEL
          value: "debug"
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        - name: bpf-fs
          mountPath: /sys/fs/bpf
        - name: kernel-headers
          mountPath: /usr/src/linux-headers
        - name: sys-kernel-debug
          mountPath: /sys/kernel/debug
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: bpf-fs
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: kernel-headers
        hostPath:
          path: /usr/src
          type: Directory
      - name: sys-kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory