apiVersion: v1
kind: ServiceAccount
metadata:
  name: conntracker
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conntracker
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conntracker
subjects:
- kind: ServiceAccount
  name: conntracker
  namespace: default
roleRef:
  kind: ClusterRole
  name: conntracker
  apiGroup: rbac.authorization.k8s.io