apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000  # Matches the Python server port
    nodePort: 30080
  selector:
    app: test-backend
